<?php
require 'db.php';
$vehicle_id=(int)($_GET['vehicle']??$_POST['vehicle_id']??0);
$stmt=$conn->prepare('SELECT * FROM vehicles WHERE id=?'); $stmt->bind_param('i',$vehicle_id); $stmt->execute(); $vehicle=$stmt->get_result()->fetch_assoc();
if(!$vehicle) die('Vehicle not found. Please go back and choose a vehicle.');
$error=''; $bill=null;
if($_SERVER['REQUEST_METHOD']==='POST'){
  $name=trim($_POST['customer_name']??''); $phone=trim($_POST['phone']??''); $email=trim($_POST['email']??''); $start=$_POST['start_date']??''; $end=$_POST['end_date']??'';
  if($name===''||!preg_match('/^[0-9]{10}$/',$phone)||!filter_var($email,FILTER_VALIDATE_EMAIL)||$start===''||$end==='') $error='Please enter all details correctly.';
  else { try { $s=new DateTime($start); $e=new DateTime($end); if($e<$s) throw new Exception('End date must be after start date.'); $days=$s->diff($e)->days+1; $total=$days*(int)$vehicle['price_per_day']; $ins=$conn->prepare('INSERT INTO bookings (vehicle_id,customer_name,phone,email,start_date,end_date,total_amount) VALUES (?,?,?,?,?,?,?)'); $ins->bind_param('isssssi',$vehicle_id,$name,$phone,$email,$start,$end,$total); if(!$ins->execute()) throw new Exception('Booking could not be saved.'); $bill=['id'=>$ins->insert_id,'name'=>$name,'phone'=>$phone,'email'=>$email,'start'=>$start,'end'=>$end,'days'=>$days,'rate'=>$vehicle['price_per_day'],'total'=>$total]; } catch(Exception $ex){$error=$ex->getMessage();} }
}
$today=date('Y-m-d');
$upi='2205.stkabirnrnp@okicici'; $upi_link='upi://pay?pa='.rawurlencode($upi).'&pn='.rawurlencode('Kalash Shah').'&cu=INR'.($bill?'&am='.rawurlencode(number_format($bill['total'],2,'.','')).'&tn='.rawurlencode('Vehicle Rental Booking #'.$bill['id']):'');
?>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>Book Vehicle</title><link rel="stylesheet" href="theme.css?v=20260930"></head><body>
<header class="site-header"><div class="nav-inner"><a class="brand" href="index.php"><span class="brand-mark">VR</span><span class="brand-name">Vehicle<span>Rental</span></span></a><nav class="main-nav"><a href="index.php">Home</a><a href="vehicles.php">Vehicles</a><a href="about.php">About</a></nav><a class="header-cta" href="vehicles.php">Book a Vehicle <span>→</span></a></div></header>
<section class="booking-page"><div class="booking-wrap"><div class="booking-card"><img class="booking-photo" src="<?= htmlspecialchars($vehicle['image']) ?>" alt="<?= htmlspecialchars($vehicle['vehicle_name']) ?>"><h1>Book <?= htmlspecialchars($vehicle['vehicle_name']) ?></h1><p class="rate">₹<?= number_format($vehicle['price_per_day']) ?> / day</p>
<?php if($error): ?><div class="error"><?= htmlspecialchars($error) ?></div><?php endif; ?>
<?php if(!$bill): ?><form method="post" id="bookingForm" onsubmit="return validateBooking()"><input type="hidden" name="vehicle_id" value="<?= $vehicle_id ?>"><label>Customer Name</label><input name="customer_name" id="customer_name" required><label>Phone Number</label><input name="phone" id="phone" maxlength="10" required><label>Email</label><input type="email" name="email" id="email" required><div class="two"><div><label>Start Date</label><input type="date" name="start_date" id="start_date" min="<?= $today ?>" required></div><div><label>End Date</label><input type="date" name="end_date" id="end_date" min="<?= $today ?>" required></div></div><div id="liveBill" class="bill-preview">Select both dates to calculate your bill.</div><button class="btn full" type="submit">Confirm Booking & Show Bill</button></form>
<?php else: ?><div class="bill"><h2>Booking Bill</h2><div class="bill-grid"><p><b>Booking ID</b><br>#<?= $bill['id'] ?></p><p><b>Customer</b><br><?= htmlspecialchars($bill['name']) ?></p><p><b>Vehicle</b><br><?= htmlspecialchars($vehicle['vehicle_name']) ?></p><p><b>Dates</b><br><?= htmlspecialchars($bill['start']) ?> to <?= htmlspecialchars($bill['end']) ?></p><p><b>Rental Days</b><br><?= $bill['days'] ?></p><p><b>Rate / Day</b><br>₹<?= number_format($bill['rate']) ?></p></div><div class="total">Total Amount: ₹<?= number_format($bill['total']) ?></div><button class="pay-btn" onclick="showQR()">Pay ₹<?= number_format($bill['total']) ?></button><div id="qrBox" class="qr-box hidden"><h2>Scan & Pay</h2><img src="qr_code.png" alt="UPI QR Code"><p><b>Kalash Shah</b></p><p>UPI: <?= htmlspecialchars($upi) ?></p><a class="upi-btn" href="<?= htmlspecialchars($upi_link) ?>">Open UPI App</a><div class="payment-done"><b>Completed your payment?</b><br><button type="button" class="btn confirm-button" id="confirmPaymentBtn" onclick="confirmPayment(); return false;">I Have Paid — Show Confirmation</button></div><div class="booking-confirmed" id="bookingConfirmation"><div class="confirm-icon">✓</div><div><h3>Booking Confirmed</h3><p>Your booking has been successfully confirmed.</p><p><b>Booking ID:</b> #<?= $bill['id'] ?> &nbsp; | &nbsp; <b>Vehicle:</b> <?= htmlspecialchars($vehicle['vehicle_name']) ?></p><p><b>Customer:</b> <?= htmlspecialchars($bill['name']) ?></p><p><b>Rental Period:</b> <?= htmlspecialchars($bill['start']) ?> to <?= htmlspecialchars($bill['end']) ?></p><p class="confirm-total">Total Paid: ₹<?= number_format($bill['total']) ?></p></div></div></div></div><?php endif; ?></div></section>
<script>window.vehicleRate=<?= (int)$vehicle["price_per_day"] ?>;</script><script src="script.js?v=20260930"></script></body></html>
