<?php require 'db.php'; ?>
<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Vehicle Rental | Drive Your Way</title><link rel="stylesheet" href="theme.css?v=20260930"></head>
<body>
<header class="site-header"><div class="nav-inner"><a class="brand" href="index.php"><span class="brand-mark">VR</span><span class="brand-name">Vehicle<span>Rental</span></span></a><nav class="main-nav"><a class="active" href="index.php">Home</a><a href="vehicles.php">Vehicles</a><a href="about.php">About</a></nav><a class="header-cta" href="vehicles.php">Book a Vehicle <span>→</span></a></div></header>
<main>
<section class="hero-premium"><div class="hero-grid"><div class="hero-copy"><div class="hero-kicker"><i></i> EASY • FAST • RELIABLE</div><h1 class="hero-title">Your journey.<span class="accent">Your vehicle.</span></h1><p class="hero-subtitle">Discover cars, bikes and scooters for every kind of trip. Choose your ride, select your dates and get a clear rental bill in minutes.</p><div class="hero-actions"><a class="primary-btn" href="vehicles.php">Explore our fleet <span>→</span></a><a class="secondary-btn" href="#fleet">See vehicles</a></div><div class="hero-stats"><div class="hero-stat"><span class="stat-number">14+</span><span class="stat-label">Vehicles</span></div><div class="hero-stat"><span class="stat-number">03</span><span class="stat-label">Categories</span></div><div class="hero-stat"><span class="stat-number">24/7</span><span class="stat-label">Easy booking</span></div></div></div><div class="hero-showcase"><div class="showcase-glow"></div><div class="showcase-card"><span class="showcase-badge">AVAILABLE NOW</span><div class="showcase-content"><span class="showcase-tag">FEATURED RIDE</span><h2>Drive Your Way.</h2><p>Cars • Bikes • Scooters</p></div></div><div class="floating-card"><div class="floating-icon">✓</div><div><b>Simple booking</b><small>Bill calculated instantly</small></div></div></div></div></section>
<section id="fleet" class="section-wrap"><div class="section-heading"><div><span class="eyebrow">Our fleet</span><h2 class="section-title">Choose what moves you.</h2></div><p class="section-description">Comfortable cars, stylish bikes and practical scooters for everyday travel, weekend plans and special journeys.</p></div><div class="cards">
<?php $result=$conn->query("SELECT * FROM vehicles WHERE status='Available' ORDER BY FIELD(vehicle_type,'Car','Bike','Scooter'), vehicle_name LIMIT 6"); while($v=$result->fetch_assoc()): ?>
<article class="vehicle-card"><div class="vehicle-image"><img src="<?= htmlspecialchars($v['image']) ?>" alt="<?= htmlspecialchars($v['vehicle_name']) ?>" loading="lazy"><span class="vehicle-status">Available</span></div><div class="vehicle-body"><span class="vehicle-type"><?= htmlspecialchars($v['vehicle_type']) ?></span><h3 class="vehicle-name"><?= htmlspecialchars($v['vehicle_name']) ?></h3><div class="vehicle-bottom"><div class="vehicle-price">₹<?= number_format($v['price_per_day']) ?> <small>/ day</small></div><a class="book-mini" href="booking.php?vehicle=<?= (int)$v['id'] ?>">Book</a></div></div></article>
<?php endwhile; ?></div><div class="center"><a class="outline-btn" href="vehicles.php">View complete fleet →</a></div></section>
<section class="feature-band"><div class="feature-grid"><div class="feature-item"><span class="feature-number">01 / PICK</span><h3>Choose your vehicle</h3><p>Browse the available fleet and select the ride that fits your plan.</p></div><div class="feature-item"><span class="feature-number">02 / PLAN</span><h3>Select your dates</h3><p>Enter your rental period and see your rental days and amount instantly.</p></div><div class="feature-item"><span class="feature-number">03 / CONFIRM</span><h3>Pay & get confirmed</h3><p>View the complete bill, scan the UPI QR and display your booking confirmation.</p></div></div></section>
<section class="about-section"><div class="about-inner"><span class="eyebrow">About the project</span><h2 class="section-title">A clean rental experience, built for real bookings.</h2><p class="about-copy">Vehicle Rental is a student mini project built with HTML, CSS, JavaScript, PHP and MySQL. It demonstrates vehicle browsing, customer details, date-based billing, database booking records and a simple UPI payment flow.</p><div class="contact-grid"><div class="contact-card"><div class="contact-icon">KS</div><div><h3>Kalash Shah</h3><p><strong>63512296959</strong></p><p>Owner & booking contact</p></div></div><div class="contact-card"><div class="contact-icon">MS</div><div><h3>Moksha Shah</h3><p><strong>9737984084</strong></p><p>Owner & booking contact</p></div></div></div></div></section>
</main><footer class="site-footer"><div class="footer-inner"><div><span class="footer-brand">Vehicle<span>Rental</span></span> &nbsp;•&nbsp; Your ride, your way.</div><div>© <?= date('Y') ?> Vehicle Rental System</div></div></footer>
</body></html>
